const types = {
  LOGIN_START: "LOGIN_START",
  LOGIN_FINISHED: "LOGIN_FINISHED",
  LOGIN_ERROR: "LOGIN_ERROR",
  GOOGLE_LOGIN_START: "GOOGLE_LOGIN_START",
  GOOGLE_LOGIN_FINISHED: "GOOGLE_LOGIN_FINISHED",
  GOOGLE_LOGIN_ERROR: "GOOGLE_LOGIN_ERROR",
  LOGOUT_START: "LOGOUT_START",
  LOGOUT_FINISHED: "LOGOUT_FINISHED",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  REGISTER_START: "REGISTER_START",
  REGISTER_FINISHED: "REGISTER_FINISHED",
  REGISTER_ERROR: "REGISTER_ERROR",
};

export default types;
