const types = {
  TRUCK_LOCATION_FETCH_START: "TRUCK_LOCATION_FETCH_START",
  TRUCK_LOCATION_FETCH_FINISHED: "TRUCK_LOCATION_FETCH_FINISHED",
  TRUCK_LOCATION_FETCH_ERROR: "TRUCK_LOCATION_FETCH_ERROR",
};

export default types;
