const types = {
  TRUCK_LOCATION_FETCH_START: "TRUCK_LOCATION_FETCH_START",
  TRUCK_LOCATION_FETCH_FINISHED: "TRUCK_LOCATION_FETCH_FINISHED",
  TRUCK_LOCATION_FETCH_ERROR: "TRUCK_LOCATION_FETCH_ERROR",
  TRUCK_LOCATION_UPDATE_START: "TRUCK_LOCATION_UPDATE_START",
  TRUCK_LOCATION_UPDATE_FINISHED: "TRUCK_LOCATION_UPDATE_FINISHED",
  TRUCK_LOCATION_UPDATE_ERROR: "TRUCK_LOCATION_UPDATE_ERROR",
};

export default types;
