const types = {
  REVIEW_FETCH_START: "REVIEW_FETCH_START",
  REVIEW_FETCH_FINISHED: "REVIEW_FETCH_FINISHED",
  REVIEW_FETCH_ERROR: "REVIEW_FETCH_ERROR",
  REVIEW_ADD_START: "REVIEW_ADD_START",
  REVIEW_ADD_FINISHED: "REVIEW_ADD_FINISHED",
  REVIEW_ADD_ERROR: "REVIEW_ADD_ERROR",
};

export default types;
