const types = {
  USER_FETCH_START: "USER_FETCH_START",
  USER_FETCH_FINISHED: "USER_FETCH_FINISHED",
  USER_FETCH_ERROR: "USER_FETCH_ERROR",
  RESET_USER_INFO: "RESET_USER_INFO",
  ADD_FAVORITE_START: "ADD_FAVORITE_START",
  ADD_FAVORITE_FINISHED: "ADD_FAVORITE_FINISHED",
  ADD_FAVORITE_ERROR: "ADD_FAVORITE_ERROR",
  REMOVE_FAVORITE_START: "REMOVE_FAVORITE_START",
  REMOVE_FAVORITE_FINISHED: "REMOVE_FAVORITE_FINISHED",
  REMOVE_FAVORITE_ERROR: "REMOVE_FAVORITE_ERROR",
  UPLOAD_IMAGE_START: "UPLOAD_IMAGE_START",
  UPLOAD_IMAGE_ERROR: "UPLOAD_IMAGE_ERROR",
  UPLOAD_IMAGE_FINISHED: "UPLOAD_IMAGE_FINISHED",
};

export default types;
