const types = {
  USER_FETCH_START: "USER_FETCH_START",
  USER_FETCH_FINISHED: "USER_FETCH_FINISHED",
  USER_FETCH_ERROR: "USER_FETCH_ERROR",
  RESET_USER_INFO: "RESET_USER_INFO",
};

export default types;
